version: "3"
services:
  web:
    image: php:8.2-apache
    volumes:
      - ./sigto:/var/www/html
    ports:
      - 80:80

  backOffice:
    image: php:8.2-apache
    volumes:
      - ./sigto/backoffice:/var/www/html
    ports:
      - 81:80